version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nhuthao
      POSTGRES_DB: kientruc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    env_file:
      - .env
    networks:
      - backend

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: